const state={role:'student',page:'dashboard',user:'Aluno'};
const courses=[{name:'Introdução à Gestão',meta:'Curso Livre • 20 horas',progress:72},{name:'Atendimento e Vendas',meta:'Curso Livre • 15 horas',progress:45},{name:'Informática Essencial',meta:'Curso Livre • 25 horas',progress:100},{name:'Comunicação Profissional',meta:'Curso Livre • 12 horas',progress:18}];
const navs={student:[['dashboard','⌂','Início'],['courses','▣','Meus cursos'],['messages','✉','Mensagens'],['certificates','★','Certificados']],teacher:[['dashboard','⌂','Painel'],['classes','▣','Minhas turmas'],['content','＋','Conteúdo das aulas'],['students','♙','Alunos'],['messages','✉','Mensagens']],manager:[['dashboard','⌂','Dashboard'],['users','♙','Usuários'],['courses','▣','Cursos'],['enrollments','✓','Matrículas'],['reports','▤','Relatórios'],['settings','⚙','Configurações']]};
const titles={dashboard:'Dashboard',courses:'Meus cursos',messages:'Mensagens',certificates:'Certificados',classes:'Minhas turmas',content:'Conteúdo das aulas',students:'Alunos',users:'Usuários',enrollments:'Matrículas',reports:'Relatórios',settings:'Configurações'};
// O e-mail do gestor será definido quando o usuário informar qual e-mail deve ter acesso administrativo.
const GESTOR_EMAIL='SEU_EMAIL_AQUI';
function $(id){return document.getElementById(id)}
function openLogin(){$('landingScreen').classList.add('hidden');$('loginScreen').classList.remove('hidden');window.scrollTo(0,0)}
$('landingLogin').onclick=openLogin;$('heroLogin').onclick=openLogin;$('backLanding').onclick=()=>{$('loginScreen').classList.add('hidden');$('landingScreen').classList.remove('hidden');window.scrollTo(0,0)};
function renderNav(){$('mainNav').innerHTML=navs[state.role].map(([id,icon,label])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}">${icon} <span>${label}</span></button>`).join('');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()})}
function studentDashboard(){return `<div class="welcome"><div><h1>Olá, ${state.user} 👋</h1><p>Continue seus estudos de onde parou.</p></div></div><div class="cards"><div class="stat-card"><span>Cursos ativos</span><strong>4</strong></div><div class="stat-card"><span>Aulas concluídas</span><strong>18</strong></div><div class="stat-card"><span>Progresso médio</span><strong>59%</strong></div><div class="stat-card"><span>Certificados</span><strong>1</strong></div></div><div class="grid"><div class="panel"><h3>Continue estudando</h3><div class="course-list">${courses.map(course).join('')}</div></div><div class="panel"><h3>Próximas atividades</h3><div class="empty">Nenhuma atividade pendente.<br><small>Novas atividades aparecerão aqui.</small></div></div></div>`}
function course(c){return `<div class="course-card"><div class="course-cover">ME</div><div class="course-info"><strong>${c.name}</strong><span>${c.meta}</span><div class="progress"><i style="width:${c.progress}%"></i></div></div><button class="action">Abrir</button></div>`}
function teacherDashboard(){return `<div class="welcome"><div><h1>Painel do professor</h1><p>Gerencie suas turmas, aulas e comunicação com os alunos.</p></div><button class="action">＋ Nova aula</button></div><div class="cards"><div class="stat-card"><span>Turmas ativas</span><strong>3</strong></div><div class="stat-card"><span>Alunos</span><strong>86</strong></div><div class="stat-card"><span>Aulas publicadas</span><strong>42</strong></div><div class="stat-card"><span>Mensagens novas</span><strong>7</strong></div></div><div class="grid"><div class="panel"><h3>Minhas turmas</h3><table class="table"><tr><th>Curso</th><th>Alunos</th><th>Progresso</th></tr><tr><td>Introdução à Gestão</td><td>32</td><td>68%</td></tr><tr><td>Atendimento e Vendas</td><td>28</td><td>51%</td></tr><tr><td>Comunicação Profissional</td><td>26</td><td>73%</td></tr></table></div><div class="panel"><h3>Ações rápidas</h3><div class="course-list"><button class="action">＋ Publicar aula</button><button class="action">＋ Enviar material</button><button class="action">✉ Enviar aviso aos alunos</button></div></div></div>`}
function managerDashboard(){return `<div class="welcome"><div><h1>Área do gestor</h1><p>Controle quem é aluno, professor, cursos e matrículas.</p></div><button class="action" id="addUserBtn">＋ Cadastrar usuário</button></div><div class="cards"><div class="stat-card"><span>Alunos cadastrados</span><strong>248</strong></div><div class="stat-card"><span>Professores</span><strong>18</strong></div><div class="stat-card"><span>Cursos ativos</span><strong>10</strong></div><div class="stat-card"><span>Matrículas ativas</span><strong>64</strong></div></div><div class="panel" style="margin-top:20px"><h3>Gerenciar usuários</h3><p style="color:var(--muted);font-size:13px">Cadastre usuários e escolha se serão alunos ou professores. Nesta versão a lista fica no navegador; depois vamos conectar ao banco de dados para tornar o controle permanente e seguro.</p><div id="userManager"></div></div>`}
function renderUsers(){const users=JSON.parse(localStorage.getItem('missexplica_users')||'[]');if(!users.length){$('userManager').innerHTML='<div class="empty">Nenhum usuário criado nesta sessão. Clique em “Cadastrar usuário”.</div>';return}$('userManager').innerHTML=`<table class="table"><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Ação</th></tr>${users.map((u,i)=>`<tr><td>${u.name}</td><td>${u.email}</td><td><select data-user="${i}" class="role-change"><option value="student" ${u.role==='student'?'selected':''}>Aluno</option><option value="teacher" ${u.role==='teacher'?'selected':''}>Professor</option></select></td><td><button class="action delete-user" data-user="${i}">Remover</button></td></tr>`).join('')}</table>`;document.querySelectorAll('.role-change').forEach(el=>el.onchange=e=>{const us=JSON.parse(localStorage.getItem('missexplica_users')||'[]');us[+e.target.dataset.user].role=e.target.value;localStorage.setItem('missexplica_users',JSON.stringify(us));render()});document.querySelectorAll('.delete-user').forEach(el=>el.onclick=()=>{const us=JSON.parse(localStorage.getItem('missexplica_users')||'[]');us.splice(+el.dataset.user,1);localStorage.setItem('missexplica_users',JSON.stringify(us));render()})}
function genericPage(){return `<div class="panel"><h3>${titles[state.page]}</h3><div class="empty">Esta área está preparada para receber as funções de <strong>${titles[state.page].toLowerCase()}</strong>.</div></div>`}
function render(){ $('pageTitle').textContent=titles[state.page]||'Dashboard';renderNav();$('pageContent').innerHTML=state.page==='dashboard'?(state.role==='student'?studentDashboard():state.role==='teacher'?teacherDashboard():managerDashboard()):genericPage();if(state.role==='manager'&&state.page==='dashboard'){renderUsers();$('addUserBtn').onclick=()=>{const name=prompt('Nome do usuário:');if(!name)return;const email=prompt('E-mail do usuário:');if(!email)return;const role=confirm('OK = Professor | Cancelar = Aluno')?'teacher':'student';const users=JSON.parse(localStorage.getItem('missexplica_users')||'[]');users.push({name,email,role});localStorage.setItem('missexplica_users',JSON.stringify(users));render()}}}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();const email=$('email').value.trim().toLowerCase();const role=$('loginRole').value;if(role==='manager'&&GESTOR_EMAIL!=='SEU_EMAIL_AQUI'&&email!==GESTOR_EMAIL.toLowerCase()){$('loginMessage').innerHTML='<strong>Acesso negado</strong><span>Este e-mail não está autorizado como gestor.</span>';return}state.role=role;state.page='dashboard';state.user=(email.split('@')[0]||'Usuário').replace(/[^a-zA-ZÀ-ÿ0-9 ]/g,' ');$('loginScreen').classList.add('hidden');$('platform').classList.remove('hidden');$('userAvatar').textContent=state.user.slice(0,2).toUpperCase();render()});
$('togglePassword').onclick=()=>{const i=$('password');i.type=i.type==='password'?'text':'password';$('togglePassword').textContent=i.type==='password'?'Mostrar':'Ocultar'};$('logoutBtn').onclick=()=>{$('platform').classList.add('hidden');$('landingScreen').classList.remove('hidden');$('loginForm').reset()};
