const state={role:'student',page:'dashboard',user:'Aluno'};
const courses=[
 {name:'Introdução à Gestão',meta:'Curso Livre • 20 horas',progress:72},
 {name:'Atendimento e Vendas',meta:'Curso Livre • 15 horas',progress:45},
 {name:'Informática Essencial',meta:'Curso Livre • 25 horas',progress:100},
 {name:'Comunicação Profissional',meta:'Curso Livre • 12 horas',progress:18}
];
const navs={student:[['dashboard','⌂','Início'],['courses','▣','Meus cursos'],['messages','✉','Mensagens'],['certificates','★','Certificados']],teacher:[['dashboard','⌂','Painel'],['classes','▣','Minhas turmas'],['content','＋','Conteúdo das aulas'],['students','♙','Alunos'],['messages','✉','Mensagens']],manager:[['dashboard','⌂','Dashboard'],['users','♙','Usuários'],['courses','▣','Cursos'],['enrollments','✓','Matrículas'],['reports','▤','Relatórios'],['settings','⚙','Configurações']]};
const titles={dashboard:'Dashboard',courses:'Meus cursos',messages:'Mensagens',certificates:'Certificados',classes:'Minhas turmas',content:'Conteúdo das aulas',students:'Alunos',users:'Usuários',enrollments:'Matrículas',reports:'Relatórios',settings:'Configurações'};
function $(id){return document.getElementById(id)}
function renderNav(){
 $('mainNav').innerHTML=navs[state.role].map(([id,icon,label])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}">${icon} <span>${label}</span></button>`).join('');
 document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
}
function studentDashboard(){return `<div class="welcome"><div><h1>Olá, ${state.user} 👋</h1><p>Continue seus estudos de onde parou.</p></div></div><div class="cards"><div class="stat-card"><span>Cursos ativos</span><strong>4</strong></div><div class="stat-card"><span>Aulas concluídas</span><strong>18</strong></div><div class="stat-card"><span>Progresso médio</span><strong>59%</strong></div><div class="stat-card"><span>Certificados</span><strong>1</strong></div></div><div class="grid"><div class="panel"><h3>Continue estudando</h3><div class="course-list">${courses.map(c=>course(c)).join('')}</div></div><div class="panel"><h3>Próximas atividades</h3><div class="empty">Nenhuma atividade pendente.<br><small>Novas atividades aparecerão aqui.</small></div></div></div>`}
function course(c){return `<div class="course-card"><div class="course-cover">UF</div><div class="course-info"><strong>${c.name}</strong><span>${c.meta}</span><div class="progress"><i style="width:${c.progress}%"></i></div></div><button class="action">Abrir</button></div>`}
function teacherDashboard(){return `<div class="welcome"><div><h1>Painel do professor</h1><p>Gerencie suas turmas, aulas e comunicação com os alunos.</p></div><button class="action">＋ Nova aula</button></div><div class="cards"><div class="stat-card"><span>Turmas ativas</span><strong>3</strong></div><div class="stat-card"><span>Alunos</span><strong>86</strong></div><div class="stat-card"><span>Aulas publicadas</span><strong>42</strong></div><div class="stat-card"><span>Mensagens novas</span><strong>7</strong></div></div><div class="grid"><div class="panel"><h3>Minhas turmas</h3><table class="table"><tr><th>Curso</th><th>Alunos</th><th>Progresso</th></tr><tr><td>Introdução à Gestão</td><td>32</td><td>68%</td></tr><tr><td>Atendimento e Vendas</td><td>28</td><td>51%</td></tr><tr><td>Comunicação Profissional</td><td>26</td><td>73%</td></tr></table></div><div class="panel"><h3>Ações rápidas</h3><div class="course-list"><button class="action">＋ Publicar aula</button><button class="action">＋ Enviar material</button><button class="action">✉ Enviar aviso aos alunos</button></div></div></div>`}
function managerDashboard(){return `<div class="welcome"><div><h1>Visão geral da plataforma</h1><p>Controle os cursos livres, usuários e matrículas.</p></div><button class="action">＋ Novo curso</button></div><div class="cards"><div class="stat-card"><span>Alunos cadastrados</span><strong>248</strong></div><div class="stat-card"><span>Cursos ativos</span><strong>10</strong></div><div class="stat-card"><span>Professores</span><strong>18</strong></div><div class="stat-card"><span>Matrículas este mês</span><strong>64</strong></div></div><div class="grid"><div class="panel"><h3>Atividade recente</h3><table class="table"><tr><th>Evento</th><th>Usuário</th><th>Status</th></tr><tr><td>Nova matrícula</td><td>Aluno #0248</td><td>Ativa</td></tr><tr><td>Novo curso</td><td>Gestor</td><td>Publicado</td></tr><tr><td>Aula atualizada</td><td>Prof. Ana</td><td>Concluído</td></tr></table></div><div class="panel"><h3>Segurança</h3><p style="color:var(--muted);font-size:13px;line-height:1.7">A versão inicial já separa os perfis. Na próxima etapa, o backend deverá controlar autenticação, permissões e liberação dos cursos conforme a matrícula.</p></div></div>`}
function genericPage(){return `<div class="panel"><h3>${titles[state.page]}</h3><div class="empty">Esta área está preparada para receber as funções de <strong>${titles[state.page].toLowerCase()}</strong>.<br>Estamos construindo o sistema por etapas.</div></div>`}
function render(){
 $('pageTitle').textContent=titles[state.page]||'Dashboard';renderNav();
 let html=state.page==='dashboard'?(state.role==='student'?studentDashboard():state.role==='teacher'?teacherDashboard():managerDashboard()):genericPage();
 $('pageContent').innerHTML=html;
}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();state.user=($('email').value.split('@')[0]||'Aluno').replace(/[^a-zA-ZÀ-ÿ0-9 ]/g,' ');$('loginScreen').classList.add('hidden');$('platform').classList.remove('hidden');render()});
$('togglePassword').onclick=()=>{const i=$('password');i.type=i.type==='password'?'text':'password';$('togglePassword').textContent=i.type==='password'?'Mostrar':'Ocultar'};
$('logoutBtn').onclick=()=>{ $('platform').classList.add('hidden');$('loginScreen').classList.remove('hidden');$('loginForm').reset()};
$('roleSelector').onchange=e=>{state.role=e.target.value;state.page='dashboard';render()};
$('notificationBtn').onclick=()=>alert('Você não possui novas notificações nesta demonstração.');
