/* MissExplica — painel de gestão com busca e filtros. */
(function(){
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 async function ensure(){const p=await window.MissExplicaData.profile();if(p.role!=='manager')throw new Error('Área exclusiva para gestores.');return p}
 async function load(){await ensure();const sb=window.missExplicaSupabase;if(!sb)throw new Error('Supabase não configurado.');const [u,c,e]=await Promise.all([sb.from('profiles').select('id,full_name,email,role,created_at').order('created_at',{ascending:false}).limit(500),sb.from('courses').select('id,title,published,teacher_id').order('title'),sb.from('enrollments').select('id,student_id,course_id,status,created_at').order('created_at',{ascending:false}).limit(1000)]);if(u.error)throw u.error;if(c.error)throw c.error;if(e.error)throw e.error;return{users:u.data||[],courses:c.data||[],enrollments:e.data||[]}}
 function render(root,data){const u=data.users,c=data.courses,e=data.enrollments;const teachers=u.filter(x=>x.role==='teacher').length,students=u.filter(x=>x.role==='student').length;root.innerHTML=`<div class="manager-panel"><header class="manager-header"><div><span class="section-tag">GESTÃO MISSEXPLICA</span><h1>Painel administrativo</h1><p>Encontre usuários rapidamente e gerencie seus acessos.</p></div><button id="managerRefresh" class="outline-btn">↻ Atualizar</button></header><section class="manager-stats"><div><strong>${u.length}</strong><span>Usuários</span></div><div><strong>${students}</strong><span>Alunos</span></div><div><strong>${teachers}</strong><span>Professores</span></div><div><strong>${e.filter(x=>x.status==='active').length}</strong><span>Matrículas ativas</span></div></section><section class="manager-card manager-users"><div class="card-title"><h2>Usuários</h2><span id="managerCount">${u.length}</span></div><div class="manager-filters"><input id="managerSearch" placeholder="Pesquisar por nome ou e-mail..." autocomplete="off"><select id="managerRoleFilter"><option value="all">Todas as funções</option><option value="student">Alunos</option><option value="teacher">Professores</option><option value="manager">Gestores</option></select></div><div id="managerUserList" class="manager-table"></div></section><section class="manager-card"><div class="card-title"><h2>Cursos</h2><span>${c.length}</span></div><div class="manager-table">${c.map(x=>`<div class="manager-row"><div><strong>${esc(x.title)}</strong><small>${x.published?'Publicado':'Rascunho'}</small></div><span class="role-badge">${e.filter(y=>y.course_id===x.id&&y.status==='active').length} alunos</span></div>`).join('')||'<p>Nenhum curso encontrado.</p>'}</div></section></div>`;
 const list=()=>{const q=($('#managerSearch')?.value||'').toLowerCase().trim(),r=$('#managerRoleFilter')?.value||'all',filtered=u.filter(x=>(r==='all'||x.role===r)&&(!q||`${x.full_name||''} ${x.email||''}`.toLowerCase().includes(q)));$('#managerCount').textContent=filtered.length;$('#managerUserList').innerHTML=filtered.map(x=>`<button class="manager-row manager-user-button" data-user="${x.id}"><div><strong>${esc(x.full_name||'Sem nome')}</strong><small>${esc(x.email||'')}</small></div><span class="role-badge role-${esc(x.role)}">${esc(x.role)}</span></button>`).join('')||'<p>Nenhum usuário encontrado.</p>';root.querySelectorAll('.manager-user-button').forEach(b=>b.onclick=()=>{const user=u.find(x=>x.id===b.dataset.user);if(user&&window.MissExplicaManagerUI)window.MissExplicaManagerUI.open(user,data)})};
 $('#managerSearch').oninput=list;$('#managerRoleFilter').onchange=list;list();$('#managerRefresh').onclick=async()=>{root.innerHTML='<div class="empty-state"><h3>Atualizando...</h3></div>';try{render(root,await load())}catch(err){root.innerHTML=`<div class="empty-state error"><h3>Erro</h3><p>${esc(err.message)}</p></div>`}};
 }
 window.MissExplicaManager={load,render};
})();
