/* MissExplica — central de notificações. */
(function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function list(limit=30){const sb=window.missExplicaSupabase;const {data,error}=await sb.from('notifications').select('id,type,title,body,link,read_at,created_at').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[]}
 async function unreadCount(){const {count,error}=await window.missExplicaSupabase.from('notifications').select('id',{count:'exact',head:true}).is('read_at',null);if(error)throw error;return count||0}
 async function markRead(id){const {error}=await window.missExplicaSupabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(error)throw error}
 async function markAllRead(){const {error}=await window.missExplicaSupabase.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);if(error)throw error}
 function render(root,items){root.innerHTML=`<section class="notifications-panel"><header><div><span class="section-tag">CENTRAL</span><h2>Notificações</h2></div><button id="readAll" class="outline-btn">Marcar todas como lidas</button></header><div class="notification-list">${items.map(n=>`<button class="notification ${n.read_at?'read':'unread'}" data-id="${esc(n.id)}" data-link="${esc(n.link||'')}"><span class="notification-icon">${n.type==='message'?'💬':n.type==='lesson'?'🎓':n.type==='course'?'📚':'🔔'}</span><span><strong>${esc(n.title)}</strong><small>${esc(n.body)}</small><time>${new Date(n.created_at).toLocaleString('pt-BR')}</time></span>${n.read_at?'':'<i></i>'}</button>`).join('')||'<div class="empty-state">Você está em dia. Nenhuma notificação.</div>'}</div></section>`;root.querySelector('#readAll').onclick=async()=>{await markAllRead();root.dispatchEvent(new CustomEvent('notifications:changed'))};root.querySelectorAll('.notification').forEach(b=>b.onclick=async()=>{await markRead(b.dataset.id);if(b.dataset.link)location.href=b.dataset.link;else root.dispatchEvent(new CustomEvent('notifications:changed'))})}
 window.MissExplicaNotifications={list,unreadCount,markRead,markAllRead,render};
})();
