-- MissExplica — progresso canônico por aluno/aula.
-- A estrutura e a RPC oficiais estão em database/lesson_progress_canonical.sql.
-- Este arquivo é mantido apenas como compatibilidade para instalações antigas.
-- Execute database/lesson_progress_canonical.sql em instalações novas ou existentes.
